# Generated by Django 5.2.7 on 2025-11-26 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_stage', models.CharField(blank=True, max_length=100)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('it', 'IT'), ('law_firm', 'Law Firm'), ('construction', 'Construction'), ('general', 'General')], default='general', max_length=100)),
                ('language', models.CharField(default='english', max_length=50)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('counterparties', models.JSONField(blank=True, default=list)),
                ('risk_score', models.IntegerField(blank=True, db_index=True, null=True)),
                ('compliance_score', models.IntegerField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('is_scanned_pdf', models.BooleanField(default=False)),
                ('ocr_method_used', models.CharField(blank=True, max_length=50)),
                ('folder_path', models.CharField(blank=True, max_length=1000)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_number', models.CharField(blank=True, max_length=50)),
                ('clause_type', models.CharField(choices=[('payment', 'Payment Terms'), ('termination', 'Termination'), ('liability', 'Liability'), ('confidentiality', 'Confidentiality'), ('intellectual_property', 'Intellectual Property'), ('force_majeure', 'Force Majeure'), ('dispute_resolution', 'Dispute Resolution'), ('governing_law', 'Governing Law'), ('warranties', 'Warranties'), ('other', 'Other')], max_length=100)),
                ('clause_category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('start_position', models.IntegerField(blank=True, null=True)),
                ('end_position', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('completeness_score', models.IntegerField(blank=True, null=True)),
                ('is_standard', models.BooleanField(default=False)),
                ('has_issues', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
            ],
            options={
                'db_table': 'clauses',
                'ordering': ['contract', 'clause_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mongo_document_id', models.CharField(max_length=100)),
                ('overall_risk_score', models.IntegerField()),
                ('critical_issues_count', models.IntegerField(default=0)),
                ('missing_clauses_count', models.IntegerField(default=0)),
                ('priority_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('processing_time', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'contract_analyses',
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', '-created_at'], name='contracts_tenant__612851_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['risk_score'], name='contracts_risk_sc_faca23_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['expiry_date'], name='contracts_expiry__fc1fec_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['file_hash'], name='contracts_file_ha_746d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['contract', 'clause_type'], name='clauses_contrac_8ef2d7_idx'),
        ),
    ]
