# Generated by Django 5.2.7 on 2025-11-26 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('counterparties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('microsoft_word', 'Microsoft Word'), ('google_docs', 'Google Docs'), ('microsoft_teams', 'Microsoft Teams'), ('slack', 'Slack'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('sap', 'SAP ERP'), ('oracle', 'Oracle ERP'), ('netsuite', 'NetSuite'), ('docusign', 'DocuSign'), ('adobe_sign', 'Adobe Sign'), ('sharepoint', 'SharePoint'), ('dropbox', 'Dropbox'), ('box', 'Box'), ('webhook', 'Custom Webhook')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('auto_sync', models.BooleanField(default=False)),
                ('sync_interval', models.CharField(default='daily', max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('purchase_order', 'Purchase Order'), ('invoice', 'Invoice'), ('contract', 'Contract')], max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=200)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('entity_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(default='synced', max_length=50)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_entities', to='contracts.contract')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_entities', to='counterparties.counterparty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_entities', to='integrations.integration')),
            ],
            options={
                'db_table': 'erp_entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_document_id', models.CharField(max_length=500)),
                ('external_document_url', models.URLField(max_length=1000)),
                ('sync_direction', models.CharField(choices=[('to_external', 'ChainSight to External'), ('from_external', 'External to ChainSight'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=50)),
                ('auto_sync', models.BooleanField(default=True)),
                ('local_version', models.IntegerField(default=1)),
                ('external_version', models.IntegerField(default=1)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('has_conflicts', models.BooleanField(default=False)),
                ('conflict_data', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_syncs', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_syncs', to='integrations.integration')),
            ],
            options={
                'db_table': 'document_syncs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('sync', 'Sync'), ('import', 'Import'), ('export', 'Export'), ('webhook', 'Webhook'), ('error', 'Error')], max_length=50)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['tenant', 'integration_type'], name='integration_tenant__d2bc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['is_active', 'is_connected'], name='integration_is_acti_f30cad_idx'),
        ),
        migrations.AddIndex(
            model_name='erpentity',
            index=models.Index(fields=['integration', 'entity_type'], name='erp_entitie_integra_6b6b79_idx'),
        ),
        migrations.AddIndex(
            model_name='erpentity',
            index=models.Index(fields=['external_id'], name='erp_entitie_externa_14beb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='erpentity',
            unique_together={('integration', 'entity_type', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='documentsync',
            index=models.Index(fields=['integration', 'contract'], name='document_sy_integra_b643bd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsync',
            index=models.Index(fields=['external_document_id'], name='document_sy_externa_480bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', '-created_at'], name='integration_integra_9c0fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['status'], name='integration_status_79d2d0_idx'),
        ),
    ]
