# Generated by Django 5.2.7 on 2025-11-26 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('review', 'Contract Review Agent'), ('compliance', 'Compliance Check Agent'), ('extraction', 'Data Extraction Agent'), ('comparison', 'Document Comparison Agent'), ('summarization', 'Summarization Agent'), ('risk_assessment', 'Risk Assessment Agent'), ('translation', 'Translation Agent'), ('redlining', 'Redlining Agent')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('total_executions', models.IntegerField(default=0)),
                ('successful_executions', models.IntegerField(default=0)),
                ('failed_executions', models.IntegerField(default=0)),
                ('last_execution_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(default='gpt-4', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_executions', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analysis.aiagent')),
            ],
            options={
                'db_table': 'agent_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('clause_id', models.UUIDField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('highlighted_text', models.TextField(blank=True)),
                ('comment_type', models.CharField(choices=[('general', 'General Comment'), ('question', 'Question'), ('issue', 'Issue/Concern'), ('suggestion', 'Suggestion'), ('approval', 'Approval')], default='general', max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contracts.contract')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='analysis.contractcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('template_text', models.TextField()),
                ('category', models.CharField(choices=[('nda', 'Non-Disclosure Agreement'), ('service', 'Service Agreement'), ('employment', 'Employment Contract'), ('lease', 'Lease Agreement'), ('sales', 'Sales Contract'), ('partnership', 'Partnership Agreement'), ('other', 'Other')], max_length=50)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('clauses', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'contract_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('comparison_type', models.CharField(choices=[('full_document', 'Full Document'), ('specific_clauses', 'Specific Clauses'), ('key_terms', 'Key Terms Only')], max_length=50)),
                ('differences', models.JSONField(blank=True, default=list)),
                ('similarities', models.JSONField(blank=True, default=list)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('redline_document_path', models.CharField(blank=True, max_length=1000)),
                ('risk_changes', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_source', to='contracts.contract')),
                ('target_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_target', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'document_comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('due_diligence', 'Due Diligence'), ('contract_review', 'Contract Review'), ('compliance_check', 'Compliance Check'), ('approval_process', 'Approval Process'), ('negotiation', 'Negotiation')], max_length=50)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('default_assignees', models.JSONField(blank=True, default=dict)),
                ('sla_hours', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('assignees', models.ManyToManyField(related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='analysis.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['tenant', 'agent_type'], name='ai_agents_tenant__c3d1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['is_active'], name='ai_agents_is_acti_ed8556_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['agent', '-created_at'], name='agent_execu_agent_i_771607_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['contract'], name='agent_execu_contrac_779c51_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['status'], name='agent_execu_status_28c835_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcomment',
            index=models.Index(fields=['contract', '-created_at'], name='contract_co_contrac_053661_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcomment',
            index=models.Index(fields=['user'], name='contract_co_user_id_25e807_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcomment',
            index=models.Index(fields=['is_resolved'], name='contract_co_is_reso_ed5047_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['tenant', 'category'], name='contract_te_tenant__f7636e_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['is_active', 'is_public'], name='contract_te_is_acti_aa0e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomparison',
            index=models.Index(fields=['tenant', '-created_at'], name='document_co_tenant__2ce594_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomparison',
            index=models.Index(fields=['source_contract'], name='document_co_source__32eff9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomparison',
            index=models.Index(fields=['target_contract'], name='document_co_target__fc3496_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['tenant', 'status'], name='workflow_in_tenant__bd9218_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['contract'], name='workflow_in_contrac_549af4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['due_date'], name='workflow_in_due_dat_e010d2_idx'),
        ),
    ]
