# Generated by Django 5.2.7 on 2025-11-26 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_users', models.IntegerField(default=10)),
                ('max_contracts', models.IntegerField(default=1000)),
                ('max_storage_gb', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_info', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['subdomain'], name='tenants_subdoma_69cf01_idx'), models.Index(fields=['status'], name='tenants_status_80d9b6_idx')],
            },
        ),
    ]
