# Generated by Django 5.2.7 on 2025-11-26 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tier', models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], max_length=20)),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('responsiveness_score', models.FloatField(blank=True, null=True)),
                ('annual_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_terms_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_monitored', models.BooleanField(default=False)),
                ('monitoring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=50)),
                ('last_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('next_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='counterparties.counterparty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['counterparty__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('assessment_type', models.CharField(choices=[('initial', 'Initial'), ('periodic', 'Periodic'), ('triggered', 'Triggered'), ('adhoc', 'Ad-hoc')], max_length=50)),
                ('overall_risk_score', models.IntegerField()),
                ('overall_risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('risk_category', models.CharField(blank=True, max_length=100)),
                ('financial_risk_score', models.IntegerField()),
                ('operational_risk_score', models.IntegerField()),
                ('compliance_risk_score', models.IntegerField()),
                ('reputational_risk_score', models.IntegerField()),
                ('geopolitical_risk_score', models.IntegerField()),
                ('cyber_security_risk_score', models.IntegerField()),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('external_data_fetched', models.BooleanField(default=False)),
                ('assessment_method', models.CharField(blank=True, max_length=100)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_assessments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'supplier_risk_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'status'], name='suppliers_tenant__a4e80e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='suppliers_supplie_e2938c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierriskassessment',
            index=models.Index(fields=['supplier', '-assessment_date'], name='supplier_ri_supplie_031ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierriskassessment',
            index=models.Index(fields=['overall_risk_level'], name='supplier_ri_overall_d77662_idx'),
        ),
    ]
