# Generated by Django 5.2.4 on 2025-07-24 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(unique=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_ip', models.GenericIPAddressField()),
                ('file', models.FileField(upload_to='contracts/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('industry', models.CharField(choices=[('garment', 'Garment'), ('it', 'Information Technology'), ('construction', 'Construction'), ('general', 'General')], max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('bengali', 'Bengali')], default='english', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_scanned_pdf', models.BooleanField(blank=True, null=True)),
                ('ocr_method_used', models.CharField(blank=True, max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_ip', 'created_at'], name='contract_ap_user_ip_4f45d0_idx'), models.Index(fields=['status'], name='contract_ap_status_242e41_idx'), models.Index(fields=['industry'], name='contract_ap_industr_5fda57_idx')],
            },
        ),
    ]
