# Generated by Django 5.2.4 on 2025-08-19 19:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(choices=[('MENA', 'MENA'), ('South Asia', 'South Asia'), ('Africa', 'Africa'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wishlist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='wishlist_email_2bde49_idx'), models.Index(fields=['region'], name='wishlist_region_2da5e1_idx'), models.Index(fields=['created_at'], name='wishlist_created_fcb55a_idx')],
            },
        ),
    ]
