# Generated by Django 5.2.4 on 2025-08-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0002_waitlish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waitlish',
            new_name='Waitlist',
        ),
    ]
