# Generated by Django 5.2.7 on 2025-11-26 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('legal_name', models.CharField(blank=True, max_length=500)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_source', models.CharField(blank=True, max_length=100)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('duns_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('external_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'counterparties',
                'db_table': 'counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractCounterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('supplier', 'Supplier'), ('contractor', 'Contractor'), ('client', 'Client'), ('vendor', 'Vendor'), ('other', 'Other')], max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_counterparties', to='contracts.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_counterparties', to='counterparties.counterparty')),
            ],
            options={
                'db_table': 'contract_counterparties',
            },
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'name'], name='counterpart_tenant__8b2264_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['registration_number'], name='counterpart_registr_da7e85_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['duns_number'], name='counterpart_duns_nu_31af48_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcounterparty',
            index=models.Index(fields=['contract'], name='contract_co_contrac_fea4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcounterparty',
            index=models.Index(fields=['counterparty'], name='contract_co_counter_de721a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractcounterparty',
            unique_together={('contract', 'counterparty', 'role')},
        ),
    ]
